apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: dangdangtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: dangthbm2k4/chiatien-backend:latest
        command: ["celery", "-A", "celery_worker.celery", "worker", "--loglevel=info"]
        env:
        - name: DB_HOST
          value: "flask-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chiatiem-secrets
              key: postgres-password
        - name: DB_NAME
          value: "postgres"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-service:6379/1"
        - name: SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: chiatiem-secrets
              key: sender-email
        - name: SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chiatiem-secrets
              key: sender-password